name: Monthly FR-JP Newsletter

on:
  schedule:
    # ⚠ GitHub Actions est en UTC : ici le 1er de chaque mois à 08:00 UTC
    - cron: '0 8 1 * *'
  workflow_dispatch: {}  # bouton Run workflow pour tester

jobs:
  build-and-send:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Paris
      OUTPUT_DIR: out
      SEND_EMAIL: "false"  # commence par false pour un dry-run
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r auto_newsletter_pack/requirements.txt

      - name: Generate config.toml from secrets
        run: |
          cat > auto_newsletter_pack/config.toml <<'EOF'
          [ai]
          openai_api_key = "${{ secrets.OPENAI_API_KEY }}"
          openai_model = "gpt-4o-mini"
          deepl_api_key = "${{ secrets.DEEPL_API_KEY }}"
          use_deepl_for_translation = true

          [content]
          rss_feeds = [
            "https://www.timeout.com/paris/en/restaurants?format=rss",
            "https://www.japantimes.co.jp/life/food/feed/",
            "https://www.timeout.com/tokyo/restaurants?format=rss"
          ]
          items_per_theme = 4
          themes = ["gastronomie", "artisanat", "design durable"]

          [content.unsplash_queries]
          gastronomie = ["kaiseki","french bistro","sake tasting","washoku"]
          artisanat = ["ceramics","woodworking Japan","wasai sewing"]
          "design durable" = ["recycled materials","upcycling","atelier design"]

          [apis]
          google_maps_api_key = ""  # optionnel
          unsplash_access_key = "${{ secrets.UNSPLASH_ACCESS_KEY }}"

          [email]
          substack_post_email = "${{ secrets.SUBSTACK_POST_EMAIL }}"
          smtp_host = "${{ secrets.SMTP_HOST }}"
          smtp_port = 587
          smtp_user = "${{ secrets.SMTP_USER }}"
          smtp_pass = "${{ secrets.SMTP_PASS }}"
          from_email = "${{ secrets.FROM_EMAIL }}"

          [run]
          output_dir = "${{ env.OUTPUT_DIR }}"
          subject_prefix = "[FR–JP Media] "
          send_email = ${SEND_EMAIL}
          EOF

      - name: Run generator
        working-directory: auto_newsletter_pack
        run: |
          python generate_newsletter.py --config config.toml

      - name: Upload generated HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: newsletter-html
          path: auto_newsletter_pack/${{ env.OUTPUT_DIR }}/*.html
