feeds:
  gastronomy:
    - https://www.japantimes.co.jp/life/food/feed/           # Japan Times (Food)
    - https://www.timeout.com/tokyo/restaurants/rss          # TimeOut Tokyo RESTAURANTS (flux section)
    - https://omakase-tour.com/en/blog/feed/                 # Blog EN (gastronomie/visites culinaire)

  craft_design:
    - https://www.dezeen.com/tag/japan/feed/                 # Dezeen - tag Japan
    - https://www.spoon-tamago.com/feed/                     # Spoon & Tamago (art/design japonais)
    - https://www.designboom.com/tag/japan/feed/             # designboom - tag Japan

  sustainability:
    - https://asia.nikkei.com/rss                            # Nikkei Asia (business/industrie, contient Japon)
    - https://www3.nhk.or.jp/nhkworld/en/news/rss/           # NHK World (news globales, fiable)
    - https://www.japantimes.co.jp/business/feed/            # JT Business (souvent GX/industrie)
