# config/sources.yml
feeds:
  gastronomy:
    - https://www.japantimes.co.jp/life/food/feed/
    - https://www.tokyoweekender.com/feed/
    - https://news.google.com/rss/search?q=tokyo+restaurant+site:japantimes.co.jp
  craft_design:
    - https://www.dezeen.com/tag/japan/feed/
    - https://spoon-tamago.com/feed/
    - https://www.designboom.com/tag/japan/feed/
  sustainability:
    - https://www.japantimes.co.jp/business/feed/
    - https://www.asahi.com/rss/asahi/eco.rdf
    - https://news.google.com/rss/search?q=Japan+green+tech+OR+GX+OR+renewables
