name: Generate FR–JP Newsletter

on:
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate newsletter
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          MISTRAL_MODEL: mistral-large-latest
          MISTRAL_MODEL_FALLBACK: open-mixtral-8x7b, ministral-8b-latest
          MAPS_EMBED_URL: ${{ secrets.MAPS_EMBED_URL }}
        run: |
          python generator/generate_newsletter.py

      - name: Commit & push site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add site/
          git commit -m "chore: update newsletter $(date +'%Y-%m-%d')" || echo "No changes"
          git push
