name: Monthly FR-JP Newsletter

on:
  schedule:
    # ⚠️ UTC : ici, le 1er de chaque mois à 08:00 UTC (≈ 09:00 Paris en été / 10:00 en hiver)
    - cron: '0 8 1 * *'
  workflow_dispatch: {}  # Permet de lancer à la main pour tester

jobs:
  build-and-send:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Paris
      OUTPUT_DIR: out
      SEND_EMAIL: "true"   # "false" = dry-run (génère le HTML mais n’envoie pas à Substack)
      MISTRAL_MODEL: mistral-large-latest  # ou mistral-small-latest / ministral-8b-latest, etc.
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r auto_newsletter_pack/requirements.txt
          # SDK Mistral (au lieu d'OpenAI)
          pip install mistralai==1.*  # ou la version stable courante

      - name: Generate config.toml (Mistral provider)
        run: |
          cat > auto_newsletter_pack/config.toml <<'EOF'
          [ai]
          # Utilisation de Mistral AI (pas d'OpenAI ici)
          mistral_api_key = "${{ secrets.MISTRAL_API_KEY }}"
          mistral_model   = "${{ env.MISTRAL_MODEL }}"
          # Si ton script garde une option de fallback, force-la côté Mistral
          use_deepl_for_translation = true

          [content]
          # Personnalise tes flux FR/JP
          rss_feeds = [
            "https://www.timeout.com/paris/en/restaurants?format=rss",
            "https://www.japantimes.co.jp/life/food/feed/",
            "https://www.timeout.com/tokyo/restaurants?format=rss"
          ]
          items_per_theme = 4
          themes = ["gastronomie", "artisanat", "design durable"]

          [content.unsplash_queries]
          gastronomie = ["kaiseki","french bistro","sake tasting","washoku"]
          artisanat = ["ceramics","woodworking Japan","wasai sewing"]
          "design durable" = ["recycled materials","upcycling","atelier design"]

          [apis]
          google_maps_api_key = ""  # optionnel
          unsplash_access_key = "${{ secrets.UNSPLASH_ACCESS_KEY }}"  # optionnel

          [email]
          substack_post_email = "${{ secrets.SUBSTACK_SUBMIT_EMAIL }}"  # adresse secrète Email-to-Post
          smtp_host = "${{ secrets.SMTP_HOST }}"
          smtp_port = 587
          smtp_user = "${{ secrets.SMTP_USER }}"
          smtp_pass = "${{ secrets.SMTP_PASS }}"
          from_email = "${{ secrets.FROM_EMAIL }}"

          [run]
          output_dir = "${{ env.OUTPUT_DIR }}"
          subject_prefix = "[FR–JP Media] "
          send_email = ${SEND_EMAIL}
          EOF

      - name: Run generator (Mistral)
        working-directory: auto_newsletter_pack
        run: |
          python generate_newsletter.py --config config.toml

      - name: Upload generated HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: newsletter-html
          path: auto_newsletter_pack/${{ env.OUTPUT_DIR }}/*.html
